name: sntr_mobile_banking_user_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'








dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  mailer: ^6.1.2
  cached_network_image: ^3.4.0
  flutter_local_notifications: ^17.2.2
  permission_handler: ^10.0.0













dev_dependencies:
  flutter_test:
    sdk: flutter


  # rules and activating additional ones.
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/

  fonts:
  - family: Great_Vibes
    fonts:
    - asset: assets/fonts/logo_font.ttf